src/MRPIIMVC/Controllers/GridController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Web.Mvc;
using System.IO;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace MRPIIMVC.Controllers
{
    public class GridController :Controller
    {
        //brought in with base controller
        private readonly Data.Phoenix db;
        public GridController(Data.Phoenix dbContext)
        {
            db = dbContext;
        }
        // GET: /<controller>/
        public IActionResult EditGrid()
        {            
            return View();
        }
        
        public async Task<IActionResult> getGrid(string name)
        {
            var vm = new Models.Grid.EditGridViewModel();
            await vm.load(name);
            await vm.updateGridFilters();
            return new JsonResult(vm);                        
        }

        public async Task<IActionResult> getGridForViewing(string name)
        {
            var vm = new Models.Grid.EditGridViewModel();
            await vm.load(name);
            await vm.loadUserSetting();
            await vm.updateGridFilters();
            return new JsonResult(vm);
        }

        [HttpPost]
        public async Task<IActionResult> SaveGrid()
        {
            string json = "";
            using (var reader = new StreamReader(Request.Body))
            {
                json = reader.ReadToEnd();
            }
            try
            {
                var vm = Newtonsoft.Json.JsonConvert.DeserializeObject<Models.Grid.EditGridViewModel>(json);
                await vm.save();
                return new JsonResult(vm);
            }
            catch (Exception error)
            {
                Response.StatusCode = 400;
                return Content("error" + error.Message);

            }
        }

        [HttpPost]
        public async Task<IActionResult> updateGridFilters()
        {
            string json = "";
            using (var reader = new StreamReader(Request.Body))
            {              
                json = reader.ReadToEnd();
            }
            try
            {
                var vm = Newtonsoft.Json.JsonConvert.DeserializeObject<Models.Grid.EditGridViewModel>(json);
                await vm.updateGridFilters();
                return new JsonResult(vm);
            }
            catch (Exception error)
            {
                return Content("error" + error.Message);
            }
            
        }
        [HttpPost]
        public async Task<IActionResult> Search()
        {
            string json = "";
            using (var reader = new StreamReader(Request.Body))
            {
                json = reader.ReadToEnd();
            }
            try
            {
                var vm = Newtonsoft.Json.JsonConvert.DeserializeObject<Models.Grid.EditGridViewModel>(json);
                var data = await vm.search();
                return new JsonResult(data);
            }
            catch (Exception error)
            {
                Response.StatusCode = 400;
                return Content("error" + error.Message);

            }
        }

    }
}

src/MRPIIMVC/Views/Shared/AngularPartial.cshtml
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<script src="~/lib/angular/angular.min.js"></script>
<script src="~/lib/angular/ngAnimate.js"></script>
<script src="~/lib/angular/angular-aria.min.js.js"></script>
<script src="~/lib/angular/angular-sanitize.min.js"></script>
<script src="~/lib/angular/ui-bootstrap-tpls-0.14.3.min.js"></script>
<script src="~/lib/angular/angular-material.min.js"></script>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/angular_material/1.1.6/angular-material.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/angular_material/1.1.6/angular-material.js"></script>

src/MRPIIMVC/Views/Shared/LoginPartial.cshtml
@model MRPIIMVC.Controllers.Account.LoginModel
@{
    ViewBag.Title = "Login";
}

<h2 class="text-center">Log In</h2>
<br />
@using (Html.BeginForm("Login", "Account", new { returnUrl = ViewBag.ReturnUrl }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <fieldset>
        <div class="row">
            <div class="col-xs-6 text-right">
                @Html.LabelFor(m => m.UserName)
            </div>
            <div class="col-xs-2 k-textbox">
                @Html.TextBoxFor(m => m.UserName, new { autofocus = "" })
                @Html.ValidationMessageFor(m => m.UserName)
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-xs-6 text-right">
                @Html.LabelFor(m => m.Password)
            </div>
            <div class="col-xs-2 k-textbox">
                @Html.PasswordFor(m => m.Password)
                @Html.ValidationMessageFor(m => m.Password)
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-xs-6 text-right">
                @Html.LabelFor(m => m.RememberMe, new { @class = "checkbox" })
            </div>
            <div class="col-xs-6 text-left">
                @Html.CheckBoxFor(m => m.RememberMe)
            </div>
        </div>
        <br />
        <div class="span-12 text-center">
            <input class="k-button" type="submit" value="Log in" />
        </div>
    </fieldset>

}

src/MRPIIMVC/Views/Shared/SecurityTagHelperPartial.cshtml
@*modal popup on security tags.*@ 
<div style="visibility: hidden" ng-app="SecurityTagHelper" ng-controller="tagHelperCtrl">
    <div class="md-dialog-container" id="myStaticSecurityDialog">
        <md-dialog>
            <md-toolbar>
                <div class="md-toolbar-tools">
                    <h5 class="modal-title" id="exampleModalLabel">Security for {{selectedElement.id}} on page {{page}}</h5>
                    <span flex></span>
                    <md-button class="md-icon-button" ng-click="closeDialog()" aria-label="close">
                        <span class="glyphicon glyphicon-remove"></span>
                    </md-button>
                </div>
            </md-toolbar>
            <md-content>
                <div layout="row">
                    <table class="table table-boardered">
                        <thead>
                            <tr>
                                <td>Company</td>
                                <td>Security Group</td>
                                <td>Match Group</td>
                                <td>Hide Control</td>
                                <td>Replace Control</td>
                                <td></td>
                            </tr>
                        </thead>
                        <tbody>
                            <tr ng-repeat="r in selectedElement.rules">
                                <td>
                                    <md-input-container ng-click="setPattern()">
                                        <label>Companies</label>
                                        <md-select ng-model="r.companyies" multiple ng-click="checkMissingSelect()">
                                            <md-option ng-value="opt" ng-repeat="opt in vm.companies">{{opt}}</md-option>
                                        </md-select>
                                    </md-input-container>
                                </td>
                                <td>
                                    <md-input-container ng-click="setPattern()">
                                        <label>Access Groups</label>
                                        <md-select ng-model="r.securityGroups" multiple ng-click="checkMissingSelect()">
                                            <md-option ng-value="opt.id" ng-repeat="opt in vm.securityGroups">{{opt.name}}</md-option>
                                        </md-select>
                                    </md-input-container>
                                </td>
                                <td>
                                    <md-checkbox ng-model="r.match" aria-label="Match">
                                    </md-checkbox>
                                </td>
                                <td>
                                    <md-checkbox ng-model="r.hide" aria-label="Hide Control">
                                    </md-checkbox>
                                </td>
                                <td>
                                    <md-input-container class="md-block">
                                        <label>Replacement</label>
                                        <textarea ng-model="r.replaceContent" md-maxlength="500" rows="2" md-select-on-focus></textarea>
                                    </md-input-container>
                                </td>
                                <td>
                                    <md-button class="md-raised" ng-click="suggestContent(r)"><span class="glyphicon glyphicon-pencil"></span></md-button>
                                </td>
                                <td>
                                    <md-button class="md-warn md-raised"><span class="glyphicon glyphicon-remove"> </span></md-button>
                                </td>
                            </tr>
                            <tr ng-click="addRule()" class="btn md-primary md-raised">
                                <td colspan="3">Add Rule </td>

                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="modal-footer" layout="row">
                    <div flex></div>
                    <md-button flex="20" class="md-raised md-primary md-right " data-dismiss="modal">Close</md-button>
                    <md-button flex="25" class="md-raised md-primary md-right" ng-click="saveSecurity()">Save</md-button>                    
                </div>
            </md-content>
        </md-dialog>
    </div>
</div>


<script>
$(document).ready(function () {
    $(".security").after(function () {
        return '<span class="glyphicon glyphicon-cog securty-clog" style="top:-12px; position:relative"> </span>'
    });
    $(".securty-clog").click(function (a, b, c) {
        var appElement = document.querySelector('[ng-app=SecurityTagHelper]');
        var appScope = angular.element(appElement).scope();
        var target = a.target.previousSibling;
        appScope.show(target);
        appScope.$apply();
    });
    var todoRootNode = jQuery('[ng-controller=tagHelperCtrl]');
    angular.bootstrap(todoRootNode, ['SecurityTagHelper']);
});


var app =angular.module("SecurityTagHelper", ['ui.bootstrap', 'ngMaterial'])
 .controller("tagHelperCtrl", ['$scope', '$http', '$mdDialog', function (scope, $http, $mdDialog) {

     $http.get(window.urlBase + "security/getPageSecurity?path="+ window.urlPath+"&cacheBreak=" + new Date().valueOf())
                  .then(function mySuccess(response) {
                      scope.vm = response.data;
                      
                  }, function myError(response) {
                      toastr.error("Failed to load tasks", '')
                  });
     scope.page= "@Context.Request.Path"
     scope.show = function (element) {
     scope.ele = element;
     scope.selectedElement = false;
     if (scope.vm.page) {
         for (var j = 0, it; it = scope.vm.page.secElements[j]; j++) {
             if (it.id == element.id) {
                 scope.selectedElement = it;
             }
         }
     }
     if (scope.vm.layoutPage) {
         for (var j = 0, it; it = scope.vm.layoutPage.secElements[j]; j++) {
             if (it.id == element.id) {
                 scope.selectedElement = it;
             }
         }
     }

         if (!scope.selectedElement)
             scope.selectedElement = { id: element.id, rules: [], }        
         //$("#SecurityTagHelper").modal()
         scope.test = $mdDialog.show({
             clickOutsideToClose: true,
             contentElement: '#myStaticSecurityDialog',
             parent: angular.element(document.body)
         });

     }
     scope.addRule = function () {
         scope.selectedElement.rules.push({ companyies: [], securityGroups :[], match:false, hide:false, replaceContent:"" });
     }
     scope.suggestContent=function(rule)
     {
         var a = scope.ele;
         rule.replaceContent = scope.selectedElement.content
         
     }
     scope.saveSecurity = function () {
         $http({
             url: window.urlBase + "Security/SaveSecurityPage?cacheBreak=" + new Date().valueOf() + "&userId=" + scope.userId,
             method: "POST",
             data: scope.vm,
             headers: { 'Content-Type': 'application/json' }
         }).then(function mySuccess(response) {
            
             toastr.success("Event Saved")
         }, function myError(response) {
             toastr.error("Failed to Save Event", response.data)
         });

     }
     scope.closeDialog = function () {
         $mdDialog.hide()
     }
     scope.closeOptions = function () { // convuluted code to hide the select window in modals
        
         if (scope.patternOpen == 2)
             $('md-select-menu').hide()
         if (scope.patternOpen === true) {
             setTimeout(function () { $('md-select-menu').show() }, 600)
         }
         if (scope.patternOpen)
             scope.patternOpen = 2
     }
     scope.checkMissingSelect = function () {
         setTimeout(function () { $('md-select-menu').show() }, 600)
     }
     scope.setPattern = function () {
         scope.patternOpen = true;
     }
 }]);


</script>

src/MRPIIMVC/Views/Shared/VuePartial.cshtml
<script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.auto.min.js"></script>
<link href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons' rel="stylesheet">

@using MRPIIMVC.Helpers



@if (Html.IsDebug())
{
    <script src="~/lib/Vue/vue.js" ></script>
}
else
{
    <script src="~/lib/Vue/vue-min.js"></script >
}
@*<script src="~/lib/Vue/bootstrap-vue.js"></script>*@
<script src="~/lib/Vue/vue-resource.min.js"></script>@*$http*@
<script src="~/lib/Vue/uiv.min.js"></script>
<script>     
</script>

src/MRPIIMVC/Views/Shared/_Layout.cshtml
@inject MRPIIMVC.Models.Account.User currentUser
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MRPIIMVC</title>

    <script>
                    window.urlBase = '@Url.Content("~/")'
        window.urlPath = '@Context.Request.Path'    
        
    </script>
   
    <link rel="stylesheet" href="~/lib/toastr.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <script src="~/lib/jquery.min.js"></script>
    @*<script src="~/lib/angular/material.min.js"></script>
        <link href="~/lib/angular/angular-material-min.css" rel="stylesheet" />*@

    <script src="~/lib/toastr.min.js"></script>

    <script src="~/lib/Kendo/kendo.all.min.js"></script>
    <link href="~/lib/Kendo/kendo.common.min.css" rel="stylesheet" />
    <link href="~/lib/Kendo/kendo.default.min.css" rel="stylesheet" />

    <link href="https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify.min.css" rel="stylesheet">

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />

   
    <script src="https://cdn.jsdelivr.net/npm/vue@2.x/dist/vue.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.6.15/browser-polyfill.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify.js"></script>

    @RenderSection("head", required: false)
 

    @*<link href="~/lib/Vue/bootstrap.min.css" rel="stylesheet" />  
    <link href="~/lib/Vue/bootstrap-vue.css" rel="stylesheet" />*@
    <link href="~/lib/bootstrap.min.css" rel="stylesheet" />

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @if (Context.Request.Query["sec"] == "1")
    {
        <script src="~/js/securityTagHelper.js"></script>
    }
    <style>
        body {
            padding-top: 0px;
            padding-bottom: 0px;
            font-size:1.5em;
        }
    </style>

</head>
<body>
    @if (ViewBag.hideSharedLayout == true)
    {
        <style>
            .wrapper {
                margin-left: 0px;
                height: 100%;
            }
        </style>
        <div id="container" class="container-fluid body-content">
            @RenderBody()


            @if (Context.Request.Query["sec"] == "1")
                {
                @Html.Partial("SecurityTagHelperPartial")
                }
        </div>
    }
    else
    {
        <div class="wrapper">
            <div id="container" class="container-fluid body-content">
                @RenderBody()


                @if (Context.Request.Query["sec"] == "1")
                {
                    @Html.Partial("SecurityTagHelperPartial");
                }
            </div>
        </div>
        //Fixed to top and listed after wrapper so the sub menues are on top of wrapper
        <div class="navbar navbar-inverse navbar-fixed-left" style="position:fixed; top:0px; display:block; padding:0; ">
            @*<a class="navbar-brand" href="#">LOGO</a>*@
            @if (currentUser.userName != null)
            {

                <div id="Schedule" class="dropdown" style="min-width:100%">
                    <button class="btn " style="min-width:100%; margin-bottom:5px;">
                        <div><span class="glyphicon glyphicon-time bigIcon"></span></div>
                        <div>Schedule</div>
                    </button>
                    <div class="dropdown-content">
                        <security tag="a" id="securityLink" page="Layout" href="@Url.Action("Schedule", "Schedule")">Schedule </security>
                        <a asp-controller="schedule" asp-action="Prepress">Prepress</a>

                        <security tag="a" id="HolidayCalendarLink" page="Layout" href="@Url.Action("HolidayCalendar", "Schedule")">Holiday Calendar</security>
                    </div>
                </div>
                @*<div class="dropdown" style="min-width:100%">
                        <button class="btn" style="min-width:100%; margin-bottom:5px;">
                            <div><span class="glyphicon glyphicon-cog bigIcon"></span></div>
                            <div>Admin</div>
                        </button>
                        <div class="dropdown-content">

                        </div>
                    </div>*@
            }
            <div class="dropdown" style="min-width:100%">
                <button class="btn" style="min-width:100%; margin-bottom:5px;">
                    <div><span class="glyphicon glyphicon-user bigIcon"></span></div>
                    <div>@currentUser.userName</div>
                </button>
                <div class="dropdown-content">
                    <a asp-area="" asp-controller="Account" asp-action="LogOff">@currentUser.userName Log Off</a>
                    @if (currentUser.userName == "suser")
                    {
                        <a asp-controller="Grid" asp-action="editGrid">Edit Grids</a>
                        <a asp-area="" asp-controller="Home" asp-action="About">About</a>
                    }
                </div>
            </div>

        </div>
    }

   

    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
    </script>

    
    <environment exclude="Development">
        <script src="~/js/directives/filteredGrid.js" asp-append-version="true"></script>
    </environment>
    <environment names="Development">
        <script src="~/js/directives/filteredGrid.js"></script>
    </environment>
    <script src="~/js/prototypes.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>